CREATE TABLE expense (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount           NUMERIC(12, 2)           NOT NULL CHECK (amount > 0),
    description      VARCHAR(120)             NOT NULL,
    expense_date     DATE                     NOT NULL,
    category         VARCHAR(30)              NOT NULL,
    payment_method   VARCHAR(30)              NOT NULL,
    source           VARCHAR(10)              NOT NULL,
    voice_transcript VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_expense_date ON expense (expense_date);
