-- Cuentas de usuario. Las contraseñas se guardan solo como hash (BCrypt), nunca en texto.
CREATE TABLE app_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(30)              NOT NULL,
    password_hash        VARCHAR(100)             NOT NULL,
    role                 VARCHAR(10)              NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    active               BOOLEAN                  NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

-- Cada gasto pasa a tener dueño.
-- Los gastos que ya existían quedan SIN dueño (user_id NULL): nadie los ve hasta que
-- el administrador los revise y los asigne a su cuenta desde el panel.
ALTER TABLE expense ADD COLUMN user_id BIGINT REFERENCES app_user (id);

CREATE INDEX idx_expense_user_date ON expense (user_id, expense_date);
