-- Ingresos. Un ingreso "esperado" sirve para planificar; solo los "recibidos" cuentan como dinero ingresado.
-- Al cobrarlo se cambia el estado del mismo registro: nunca se duplica.
CREATE TABLE income (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES app_user (id),
    description VARCHAR(120)             NOT NULL,
    amount      NUMERIC(12, 2)           NOT NULL CHECK (amount > 0),
    income_date DATE                     NOT NULL,
    income_type VARCHAR(20)              NOT NULL CHECK (income_type IN ('SUELDO', 'EXTRA', 'OTROS')),
    status      VARCHAR(10)              NOT NULL CHECK (status IN ('EXPECTED', 'RECEIVED')),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_income_user_date ON income (user_id, income_date);
