-- Gastos fijos: se configuran una vez y generan una obligación por mes.
-- Los meses se guardan como el día 1 de ese mes.
CREATE TABLE recurring_expense (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT                   NOT NULL REFERENCES app_user (id),
    description   VARCHAR(120)             NOT NULL,
    category      VARCHAR(30)              NOT NULL,
    amount        NUMERIC(12, 2)           NOT NULL CHECK (amount > 0),
    due_day       SMALLINT                 NOT NULL CHECK (due_day BETWEEN 1 AND 31),
    start_month   DATE                     NOT NULL CHECK (EXTRACT(DAY FROM start_month) = 1),
    end_month     DATE                     CHECK (EXTRACT(DAY FROM end_month) = 1),
    status        VARCHAR(10)              NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED')),
    -- Primer mes que se puede generar. Al reanudar después de una pausa pasa al mes actual,
    -- así no se crean obligaciones para los meses en que estuvo pausado.
    generate_from DATE                     NOT NULL CHECK (EXTRACT(DAY FROM generate_from) = 1),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (end_month IS NULL OR end_month >= start_month)
);

CREATE INDEX idx_recurring_user ON recurring_expense (user_id);

-- Una obligación = lo que hay que pagar de un gasto fijo en un mes.
-- Concepto, categoría e importe se copian al generarla: cambiar la configuración no altera meses pagados.
CREATE TABLE recurring_obligation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT                   NOT NULL REFERENCES app_user (id),
    recurring_id     BIGINT                   NOT NULL REFERENCES recurring_expense (id),
    obligation_month DATE                     NOT NULL CHECK (EXTRACT(DAY FROM obligation_month) = 1),
    due_date         DATE                     NOT NULL,
    description      VARCHAR(120)             NOT NULL,
    category         VARCHAR(30)              NOT NULL,
    amount           NUMERIC(12, 2)           NOT NULL CHECK (amount > 0),
    -- true si se ajustó el importe de este mes a mano (los cambios de configuración no lo pisan)
    amount_adjusted  BOOLEAN                  NOT NULL DEFAULT FALSE,
    status           VARCHAR(10)              NOT NULL CHECK (status IN ('PENDING', 'PAID', 'SKIPPED')),
    -- Gasto real con el que se pagó. Un gasto paga como máximo una obligación.
    expense_id       BIGINT                   REFERENCES expense (id),
    -- true si el gasto lo creó la app al pagar (al deshacer el pago se elimina); false si se vinculó uno existente
    expense_created  BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Nunca dos obligaciones del mismo gasto fijo en el mismo mes
    CONSTRAINT uk_obligation_recurring_month UNIQUE (recurring_id, obligation_month),
    CONSTRAINT uk_obligation_expense UNIQUE (expense_id),
    -- Pagada si y solo si tiene un gasto vinculado
    CONSTRAINT ck_obligation_paid_has_expense CHECK ((status = 'PAID') = (expense_id IS NOT NULL))
);

CREATE INDEX idx_obligation_user_month ON recurring_obligation (user_id, obligation_month);
