-- Presupuesto mensual por categoría. Asignar un importe no registra un gasto ni mueve dinero.
CREATE TABLE budget_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES app_user (id),
    budget_month DATE                     NOT NULL CHECK (EXTRACT(DAY FROM budget_month) = 1),
    category     VARCHAR(30)              NOT NULL,
    amount       NUMERIC(12, 2)           NOT NULL CHECK (amount >= 0),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_budget_user_month_category UNIQUE (user_id, budget_month, category)
);
